/* Aurum 2.0 global behaviour */
document.querySelectorAll('.brand img, footer img, .brochure-top img').forEach(img=>{img.src='Logo.png';img.alt='Aurum Bullion PLC'});
let fav=document.querySelector("link[rel~='icon']");if(!fav){fav=document.createElement('link');fav.rel='icon';document.head.appendChild(fav)}fav.type='image/png';fav.href='Logo.png';
const menu=document.querySelector('.menu');if(menu)menu.addEventListener('click',()=>{document.querySelector('nav')?.classList.toggle('open')});

/* Ghana field story: six clips presented as one scrub-able film, with soundtrack position locked to the film timeline. */
(function(){
 const videos=[...document.querySelectorAll('[data-ghana-video]')],frame=document.querySelector('.ghana-video-showcase'),media=document.querySelector('.ghana-media'),stills=document.querySelector('.ghana-stills');
 if(!videos.length||!frame||!media||!stills)return;
 Object.assign(media.style,{display:'grid',gridTemplateColumns:'1.15fr .85fr',gap:'10px',alignItems:'stretch',margin:'38px 0 55px'});[frame,stills].forEach(el=>Object.assign(el.style,{height:'420px',minHeight:'420px',maxHeight:'420px',margin:'0',padding:'0',alignSelf:'stretch',overflow:'hidden',background:'transparent',border:'0'}));Object.assign(frame.style,{position:'relative',width:'100%'});Object.assign(stills.style,{display:'grid',gridTemplateColumns:'1fr 1fr',gridTemplateRows:'1fr 1fr',gap:'8px'});stills.querySelectorAll('img').forEach(img=>Object.assign(img.style,{display:'block',width:'100%',height:'100%',minHeight:'0',margin:'0',objectFit:'cover',objectPosition:'center'}));
 videos.forEach((video,i)=>{Object.assign(video.style,{position:'absolute',inset:'0',width:'100%',height:'100%',objectFit:'cover',objectPosition:'center center',background:'transparent',opacity:i===0?'1':'0',visibility:i===0?'visible':'hidden',transition:'opacity .3s ease'});video.muted=true;video.defaultMuted=true;video.volume=0;video.removeAttribute('controls');video.setAttribute('muted','');video.setAttribute('playsinline','');video.addEventListener('volumechange',()=>{if(!video.muted||video.volume!==0){video.muted=true;video.volume=0}})});
 const oldDots=frame.querySelector('.ghana-video-progress');if(oldDots)oldDots.style.display='none';
 const music=document.createElement('audio');music.id='ghana-folk-music';music.loop=true;music.preload='auto';music.volume=.16;music.src='https://commons.wikimedia.org/wiki/Special:Redirect/file/Babu%20Me-Ee-Say%20Ala%20(c.1952).ogg';document.body.appendChild(music);
 let current=0,durations=videos.map(()=>0),totalDuration=0,seeking=false,musicWanted=true;
 const elapsedBefore=i=>durations.slice(0,i).reduce((a,b)=>a+b,0),filmTime=()=>elapsedBefore(current)+(videos[current].currentTime||0);
 const calcTotal=()=>{totalDuration=durations.reduce((a,b)=>a+(Number.isFinite(b)?b:0),0)};
 const syncMusic=(absoluteTime=filmTime())=>{if(!Number.isFinite(music.duration)||!music.duration)return;const target=((absoluteTime%music.duration)+music.duration)%music.duration;if(Math.abs((music.currentTime||0)-target)>.35){try{music.currentTime=target}catch(e){}}};
 videos.forEach((v,i)=>v.addEventListener('loadedmetadata',()=>{durations[i]=v.duration||0;calcTotal()}));music.addEventListener('loadedmetadata',()=>syncMusic());
 const controls=document.createElement('div');Object.assign(controls.style,{position:'absolute',left:'14px',right:'14px',bottom:'12px',zIndex:'8',display:'grid',gridTemplateColumns:'34px 1fr 34px',gap:'10px',alignItems:'center',padding:'8px 10px',background:'rgba(15,15,15,.66)',backdropFilter:'blur(3px)'});const back=document.createElement('button'),forward=document.createElement('button'),scrub=document.createElement('input');back.type=forward.type='button';back.textContent='‹';forward.textContent='›';back.setAttribute('aria-label','Previous video');forward.setAttribute('aria-label','Next video');[back,forward].forEach(b=>Object.assign(b.style,{height:'30px',border:'1px solid rgba(255,255,255,.65)',background:'transparent',color:'#fff',fontSize:'22px',lineHeight:'20px',cursor:'pointer'}));scrub.type='range';scrub.min='0';scrub.max='1000';scrub.value='0';scrub.step='1';scrub.setAttribute('aria-label','Scroll backwards or forwards through Ghana video and music');Object.assign(scrub.style,{width:'100%',cursor:'pointer',accentColor:'#d4af37'});controls.append(back,scrub,forward);frame.appendChild(controls);
 const musicButton=document.createElement('button');musicButton.type='button';musicButton.textContent='♫ Ghana music';musicButton.setAttribute('aria-label','Play or pause Ghana traditional music');Object.assign(musicButton.style,{position:'absolute',right:'12px',top:'12px',zIndex:'9',border:'1px solid rgba(255,255,255,.75)',background:'rgba(20,20,20,.68)',color:'#fff',padding:'8px 11px',fontSize:'10px',letterSpacing:'1px',cursor:'pointer'});frame.appendChild(musicButton);
 const startMusic=()=>{musicWanted=true;syncMusic();return music.play().then(()=>{musicButton.textContent='❚❚ Music'}).catch(()=>{})};musicButton.addEventListener('click',e=>{e.stopPropagation();if(music.paused){startMusic()}else{musicWanted=false;music.pause();musicButton.textContent='♫ Ghana music'}});
 const updateScrub=()=>{if(seeking||!totalDuration)return;const elapsed=filmTime();scrub.value=String(Math.max(0,Math.min(1000,(elapsed/totalDuration)*1000)));if(!music.paused)syncMusic(elapsed)};
 const show=(i,time=0,play=true)=>{current=(i+videos.length)%videos.length;videos.forEach((v,n)=>{const active=n===current;v.style.opacity=active?'1':'0';v.style.visibility=active?'visible':'hidden';if(!active)v.pause()});const v=videos[current];try{v.currentTime=Math.max(0,Math.min(time,Math.max(0,(v.duration||time)-.05)))}catch(e){}syncMusic(elapsedBefore(current)+time);if(play){v.play().catch(()=>{});if(musicWanted)startMusic()}updateScrub()};
 videos.forEach((v,i)=>{v.addEventListener('timeupdate',updateScrub);v.addEventListener('play',()=>{syncMusic();if(musicWanted)startMusic()});v.addEventListener('pause',()=>{if(!seeking&&!videos.some(x=>!x.paused))music.pause()});v.addEventListener('ended',()=>show(i+1,0,true))});
 back.addEventListener('click',e=>{e.stopPropagation();if(videos[current].currentTime>2)show(current,0,true);else show(current-1,0,true)});forward.addEventListener('click',e=>{e.stopPropagation();show(current+1,0,true)});
 scrub.addEventListener('pointerdown',()=>{seeking=true;videos[current].pause();music.pause()});scrub.addEventListener('input',()=>{if(!totalDuration)return;let target=(Number(scrub.value)/1000)*totalDuration,acc=0,index=0,local=0;for(let i=0;i<durations.length;i++){if(target<=acc+durations[i]||i===durations.length-1){index=i;local=target-acc;break}acc+=durations[i]}show(index,Math.max(0,local),false);syncMusic(target)});const finishSeek=()=>{if(!seeking)return;seeking=false;syncMusic();videos[current].play().catch(()=>{});if(musicWanted)startMusic();updateScrub()};scrub.addEventListener('change',finishSeek);scrub.addEventListener('pointerup',finishSeek);
 const firstInteraction=()=>{if(musicWanted)startMusic()};document.addEventListener('pointerdown',firstInteraction,{once:true});document.addEventListener('keydown',firstInteraction,{once:true});show(0,0,true);
 const responsive=()=>{if(window.innerWidth<=1080){Object.assign(media.style,{gridTemplateColumns:'1fr'});[frame,stills].forEach(el=>{el.style.height='min(62vw,420px)';el.style.minHeight='280px';el.style.maxHeight='420px'})}else{Object.assign(media.style,{gridTemplateColumns:'1.15fr .85fr'});[frame,stills].forEach(el=>{el.style.height='420px';el.style.minHeight='420px';el.style.maxHeight='420px'})}};responsive();window.addEventListener('resize',responsive);
})();

let goldCurrency='GBP',lastUsd=null,lastGbp=null;
function renderGold(){const el=document.getElementById('gold'),pair=document.getElementById('goldpair');if(!el)return;if(goldCurrency==='USD'&&lastUsd){el.textContent='$'+lastUsd.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})+' / TROY OZ';if(pair)pair.textContent='XAU/USD'}else if(lastGbp){el.textContent='£'+lastGbp.toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2})+' / TROY OZ';if(pair)pair.textContent='XAU/GBP'}}
async function updateGold(){const el=document.getElementById('gold'),tm=document.getElementById('goldtime');if(!el)return;try{const [g,fx]=await Promise.all([fetch('https://api.gold-api.com/price/XAU').then(r=>r.json()),fetch('https://api.frankfurter.app/latest?from=USD&to=GBP').then(r=>r.json())]);lastUsd=Number(g.price);lastGbp=lastUsd*Number(fx.rates.GBP);if(!Number.isFinite(lastUsd)||!Number.isFinite(lastGbp))throw new Error('price');renderGold();if(tm)tm.textContent='• INDICATIVE LIVE SPOT'}catch(e){el.textContent='Live spot temporarily unavailable';if(tm)tm.textContent=''}}
const toggle=document.getElementById('currencyToggle');if(toggle)toggle.addEventListener('click',()=>{goldCurrency=goldCurrency==='GBP'?'USD':'GBP';renderGold()});updateGold();setInterval(updateGold,300000);
(function(){if(localStorage.getItem('aurumCookieChoice'))return;const b=document.createElement('div');b.className='cookie-banner';b.innerHTML='<div><strong>Cookie choices</strong><p>Aurum uses necessary cookies for core site functions. Optional analytics or marketing technologies will only be activated with consent if introduced.</p></div><div><button data-cookie="necessary">Necessary only</button><button class="accept" data-cookie="all">Accept all</button><a href="cookies.html">Cookies Policy</a></div>';document.body.appendChild(b);b.querySelectorAll('[data-cookie]').forEach(x=>x.onclick=()=>{localStorage.setItem('aurumCookieChoice',x.dataset.cookie);b.remove()})})();